apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-model-deployment
spec:
  replicas: 1  # Number of instances
  selector:
    matchLabels:
      app: mlflow-model
  template:
    metadata:
      labels:
        app: mlflow-model
    spec:
      containers:
      - name: mlflow-model-container
        image: supreetsharma94/deployment_image:latest  # Use the image you built
        ports:
        - containerPort: 5000