apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-service
spec:
  type: LoadBalancer  # Or NodePort for local testing
  ports:
    - port: 5000  # Match the container port
  selector:
    app: mlflow-model