name: CI
run-name: ${{ github.actor }} is trying its first Github CI

on:
  push

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Python 3.9 environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      
      # Run our tests
      # To Do

      # Run our pipeline
      - name: Run mlflow pipeline
        run: dagster job execute -f dagster_mlflow_project/initiate_pipeline.py --job daily_refresh

      # Evaluate the model
      - name: Evaluate model
        run: |
          python dagster_mlflow_project_evaluate/evaluate.py

